# Generated by Django 4.2 on 2023-04-06 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_trait_cerated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="cerated_at",
            new_name="created_at",
        ),
    ]
